// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	tiktok "TikTokLiteV2/kitex_gen/tiktok"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

var videoServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*tiktok.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Feed":          kitex.NewMethodInfo(feedHandler, newVideoServiceFeedArgs, newVideoServiceFeedResult, false),
		"PublishAction": kitex.NewMethodInfo(publishActionHandler, newVideoServicePublishActionArgs, newVideoServicePublishActionResult, false),
		"PublishList":   kitex.NewMethodInfo(publishListHandler, newVideoServicePublishListArgs, newVideoServicePublishListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "tiktok",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func feedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*tiktok.VideoServiceFeedArgs)
	realResult := result.(*tiktok.VideoServiceFeedResult)
	success, err := handler.(tiktok.VideoService).Feed(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceFeedArgs() interface{} {
	return tiktok.NewVideoServiceFeedArgs()
}

func newVideoServiceFeedResult() interface{} {
	return tiktok.NewVideoServiceFeedResult()
}

func publishActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*tiktok.VideoServicePublishActionArgs)
	realResult := result.(*tiktok.VideoServicePublishActionResult)
	success, err := handler.(tiktok.VideoService).PublishAction(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishActionArgs() interface{} {
	return tiktok.NewVideoServicePublishActionArgs()
}

func newVideoServicePublishActionResult() interface{} {
	return tiktok.NewVideoServicePublishActionResult()
}

func publishListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*tiktok.VideoServicePublishListArgs)
	realResult := result.(*tiktok.VideoServicePublishListResult)
	success, err := handler.(tiktok.VideoService).PublishList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishListArgs() interface{} {
	return tiktok.NewVideoServicePublishListArgs()
}

func newVideoServicePublishListResult() interface{} {
	return tiktok.NewVideoServicePublishListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Feed(ctx context.Context, request *tiktok.FeedRequest) (r *tiktok.FeedResponse, err error) {
	var _args tiktok.VideoServiceFeedArgs
	_args.Request = request
	var _result tiktok.VideoServiceFeedResult
	if err = p.c.Call(ctx, "Feed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PublishAction(ctx context.Context, request *tiktok.PublishActionRequest) (r *tiktok.PublishActionResponse, err error) {
	var _args tiktok.VideoServicePublishActionArgs
	_args.Request = request
	var _result tiktok.VideoServicePublishActionResult
	if err = p.c.Call(ctx, "PublishAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PublishList(ctx context.Context, request *tiktok.PublishListRequest) (r *tiktok.PublishListResponse, err error) {
	var _args tiktok.VideoServicePublishListArgs
	_args.Request = request
	var _result tiktok.VideoServicePublishListResult
	if err = p.c.Call(ctx, "PublishList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
