// Code generated by Kitex v0.4.4. DO NOT EDIT.

package testservice

import (
	server "github.com/cloudwego/kitex/server"
	tiktok "TikTokLiteV2/kitex_gen/tiktok"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler tiktok.TestService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
