// Code generated by hertz generator.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/okatu-loli/TikTokLite/internal/handler"
)

// CustomizedRegister registers customize routers.
func CustomizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
}
