// Code generated by hertz generator.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/okatu-loli/TikTokLite/internal/handler"
	"github.com/okatu-loli/TikTokLite/internal/middleware"
)

// CustomizedRegister registers customize routers.
func CustomizedRegister(r *server.Hertz) {

	videoHandler := handler.NewVideoHandler()
	feedHandler := handler.NewFeedHandler()
	chatHandler := handler.NewChatHandler()

	r.GET("/ping", handler.Ping)

	// your code ...
	douyin := r.Group("/douyin")
	{
		//使用中间件
		//douyin.Use(basic_auth.BasicAuth(map[string]string{"test": "test"}))
		user := douyin.Group("/user")
		{
			user.POST("/register/", handler.Register)
			//user.POST("/login", handler.Login)
			//user.GET("/", handler.GetUserInfo)
			user.POST("/login/", middleware.JwtMiddleware.LoginHandler)
			user.GET("", middleware.JwtMiddleware.MiddlewareFunc(), handler.GetUserInfo)
		}

		video := douyin.Group("/publish")
		{
			video.Use(middleware.JwtMiddleware.MiddlewareFunc())
			video.POST("/action/", videoHandler.UploadVideo)
			video.GET("/list", videoHandler.PublishList)
		}

		message := douyin.Group("/message")
		{
			message.Use(middleware.JwtMiddleware.MiddlewareFunc())
			message.POST("/action/", chatHandler.SendChat)
		}

		douyin.GET("/feed", feedHandler.FeedList)
	}
}
