// Code generated by hertz generator.

package main

import (
	"go-project/TikTokLite/cmd/router"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	router.CustomizedRegister(h)
	h.Spin()
}
